[package]
name = "ferry-relay"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
iroh.workspace = true
iroh-relay = { version = "=1.0.3", features = ["server"] }
tokio = { workspace = true, features = ["signal"] }
futures-util = "0.3"
ferry-store = { path = "../ferry-store" }

tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = "0.1"

[dev-dependencies]
ferry-iroh = { path = "../ferry-iroh" }
ferry-sync = { path = "../ferry-sync" }
tempfile.workspace = true

[[bin]]
name = "ferry-relay"
path = "src/bin/ferry_relay.rs"

[lints]
workspace = true
