[package]
name = "ferry-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ferry-store = { path = "../ferry-store" }
x25519-dalek = { version = "2", features = ["static_secrets"] }
chacha20poly1305 = "0.10"
hkdf = "0.12"
sha2 = "0.10"
hmac = "0.12"
blake3 = "1.5"
rand = "0.8"
argon2 = "0.5"
zeroize = "1"
qrcode = "0.14"
thiserror = "2"

[dev-dependencies]
tempfile = "3"
