[package]
name = "ferry-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ferry-store = { path = "../ferry-store" }
x25519-dalek.workspace = true
chacha20poly1305.workspace = true
hkdf.workspace = true
sha2.workspace = true
hmac.workspace = true
blake3.workspace = true
rand.workspace = true
argon2 = "0.5"
zeroize.workspace = true
qrcode.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
