[package]
name = "ferry-sync"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ferry-store = { path = "../ferry-store" }
blake3 = "1.5"
rand = "0.8"
thiserror = "2"
ferry-platform = { path = "../ferry-platform" }
ferry-materialize = { path = "../ferry-materialize" }

[dev-dependencies]
rand = "0.8"
tempfile = "3"

[[bin]]
name = "ferry-sync"
path = "src/bin/ferry_sync.rs"
