[package]
name = "ferry-materialize"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
unicode-normalization.workspace = true
ferry-store = { path = "../ferry-store" }
ferry-platform.workspace = true
blake3.workspace = true
rand.workspace = true
thiserror.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(not(unix))'.dependencies]
filetime.workspace = true

[dev-dependencies]
ferry-store = { path = "../ferry-store", features = ["test-util"] }
tempfile.workspace = true

[lints]
workspace = true
