[package]
name = "ferry-scan"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ferry-store = { path = "../ferry-store" }
notify = "8"
blake3.workspace = true
thiserror.workspace = true
unicode-normalization.workspace = true
ferry-platform.workspace = true

[dev-dependencies]
tempfile.workspace = true
rand.workspace = true

[lints]
workspace = true
