[package]
name = "ferry-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
rand.workspace = true
hkdf.workspace = true
sha2.workspace = true
thiserror.workspace = true
unicode-normalization.workspace = true
ferry-platform.workspace = true

[features]
test-util = []

[dev-dependencies]
ferry-store = { path = ".", features = ["test-util"] }
tempfile.workspace = true

[target.'cfg(not(unix))'.dev-dependencies]
filetime.workspace = true

[lints]
workspace = true
